run:
  timeout: 5m
  go: "1.25"

issues:
  exclude-use-default: false

linters:
  enable:
    - errcheck
    - gofumpt
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unconvert
    - unused
  disable:
    - depguard

linters-settings:
  gofumpt:
    module-path: github.com/steipete/tmuxwatch
  errcheck:
    check-type-assertions: true
    check-blank: true
